# Generated by Django 2.2.7 on 2019-11-27 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191127_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(default=list, null=True, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
