# Generated by Django 2.2.7 on 2019-11-27 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191127_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owners',
            field=models.ManyToManyField(blank=True, default=list, null=True, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
