# Generated by Django 2.2.7 on 2019-11-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191127_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='share_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
