# Generated by Django 2.2.7 on 2019-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OW', 'owner'), ('IV', 'investor')], default='IV', max_length=10),
        ),
    ]
