# Generated by Django 2.2.7 on 2020-02-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
